# Generated by Django 3.1.2 on 2021-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210305_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resttimetable',
            name='end_time',
            field=models.TimeField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='resttimetable',
            name='start_time',
            field=models.TimeField(default='', max_length=255),
        ),
    ]
