# Generated by Django 3.1.2 on 2021-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210306_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resttimetable',
            name='end_time',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='resttimetable',
            name='start_time',
            field=models.TimeField(default=''),
        ),
    ]
