# Generated by Django 3.1.2 on 2021-03-07 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210306_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restcommentbox',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restcomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
