# Generated by Django 3.1.2 on 2021-03-09 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210307_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcommentbox',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemcomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
