# Generated by Django 3.1.2 on 2021-03-09 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210309_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealcommentbox',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealcomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mcdiscountcommentbox',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcdiscom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformdiscommentbox',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platformcomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
