# Generated by Django 3.1.2 on 2021-03-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20210309_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcdiscount',
            options={'verbose_name_plural': 'MealCatcherDiscounts'},
        ),
        migrations.AlterModelOptions(
            name='mcdiscountcommentbox',
            options={'verbose_name_plural': 'MealCatcherDiscountCommentBoxes'},
        ),
        migrations.AlterField(
            model_name='restbranch',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
