# Generated by Django 3.1.7 on 2021-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20210331_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='restcommentbox',
            name='rating',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restcommentbox',
            name='cust_id',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restcommentbox',
            name='rest_id',
            field=models.TextField(max_length=100),
        ),
    ]
