# Generated by Django 3.1.7 on 2021-04-27 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20210427_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restcommentbox',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restcomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restcommentbox',
            name='rest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
