# Generated by Django 3.1.7 on 2021-04-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20210427_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcommentbox',
            name='rating',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemcommentbox',
            name='rating',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
