# Generated by Django 3.1.7 on 2021-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20210428_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bad_comments',
            field=models.IntegerField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='good_comments',
            field=models.IntegerField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_comments',
            field=models.IntegerField(max_length=1000, null=True),
        ),
    ]
