# Generated by Django 3.1.7 on 2021-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20210429_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='bad_comments',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='good_comments',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='total_comments',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
