# Generated by Django 3.1.7 on 2021-04-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20210429_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='total_rating',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
