# Generated by Django 3.1.7 on 2021-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_restaurant_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='total_rating',
            field=models.FloatField(default=0.0, max_length=1000),
        ),
    ]
