# Generated by Django 3.1.7 on 2021-04-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20210429_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='bad_comments',
        ),
    ]
