# Generated by Django 3.1.7 on 2021-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_remove_restaurant_bad_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='total_rating',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
