# Generated by Django 3.1.7 on 2021-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_auto_20210429_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='good_comments',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='deal',
            name='total_comments',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='good_comments',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='total_comments',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
