# Generated by Django 3.1.7 on 2021-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20210429_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_rating',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
