# Generated by Django 3.1.7 on 2021-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_item_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='total_rating',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
