# Generated by Django 3.1.2 on 2021-04-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_deal_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='good_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_rating',
            field=models.FloatField(default=0.0, max_length=5.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='good_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='good_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
    ]
